name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

      - name: Lint code
        run: pnpm run lint
        if: always()
        id: lint

      - name: Check for lint errors
        run: |
          if [ -n "$(grep 'error' $(steps.lint.outputs.lint_output))" ]; then
            echo "Linting errors found!"
            exit 1
          fi
        if: always()
